// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMkj0Agd0BZBmksEoNTAgBGbwF6Bos9Ck',
    appId: '1:610847873364:web:03932c610d58b38f9a10c1',
    messagingSenderId: '610847873364',
    projectId: 'chatdo-48bf4',
    authDomain: 'chatdo-48bf4.firebaseapp.com',
    storageBucket: 'chatdo-48bf4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3YOPvKjE-H1hawqysLJ1HFk86i43McNw',
    appId: '1:610847873364:android:97596b1a7f26b1349a10c1',
    messagingSenderId: '610847873364',
    projectId: 'chatdo-48bf4',
    storageBucket: 'chatdo-48bf4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWIaBVqD-KVjCbl5f465QpnxAFNB_axcw',
    appId: '1:610847873364:ios:e455065e4a195a899a10c1',
    messagingSenderId: '610847873364',
    projectId: 'chatdo-48bf4',
    storageBucket: 'chatdo-48bf4.firebasestorage.app',
    iosClientId: '610847873364-29sif406plhe4tsfh6cqg3333h8m8a8a.apps.googleusercontent.com',
    iosBundleId: 'com.chatdo.chatdo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWIaBVqD-KVjCbl5f465QpnxAFNB_axcw',
    appId: '1:610847873364:ios:33efff4b67a1c76c9a10c1',
    messagingSenderId: '610847873364',
    projectId: 'chatdo-48bf4',
    storageBucket: 'chatdo-48bf4.firebasestorage.app',
    iosClientId: '610847873364-uggi11ksp33is64p119sbhr5430pufue.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatdo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMkj0Agd0BZBmksEoNTAgBGbwF6Bos9Ck',
    appId: '1:610847873364:web:1f191dbfe724cd059a10c1',
    messagingSenderId: '610847873364',
    projectId: 'chatdo-48bf4',
    authDomain: 'chatdo-48bf4.firebaseapp.com',
    storageBucket: 'chatdo-48bf4.firebasestorage.app',
  );
}
